# Generated by Django 4.2.2 on 2023-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_facedetection_faceenroll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceenroll',
            name='feature',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
