# Generated by Django 4.2.2 on 2023-06-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_faceenroll_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceEnroll',
        ),
    ]
