# Generated by Django 4.2.2 on 2023-06-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_faceenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='user_faces')),
                ('feature', models.FloatField()),
            ],
        ),
    ]
