# Generated by Django 4.2.2 on 2023-06-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_faceenroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceenroll',
            name='feature',
            field=models.FloatField(null=True),
        ),
    ]
