# Generated by Django 4.2.2 on 2023-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_faceenroll_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceenroll',
            name='feature',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
