# Generated by Django 4.2.2 on 2023-06-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_faceenroll_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceenroll',
            name='feature',
            field=models.CharField(max_length=2000),
        ),
    ]
