# Generated by Django 4.2.2 on 2023-06-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_faceenroll_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedetection',
            name='name',
        ),
        migrations.AddField(
            model_name='facedetection',
            name='face_enroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faceenroll'),
        ),
    ]
